### ISSUE TITLE
Line Breaks

### ISSUE THREAD

**Issue by MrKleeblatt** [s3ansh33p/ClasspadCompiler#1]
Hey there,
This is such an awesome tool, helps a lot! But every time I want to convert a Program to an .xcp file using `util.js` all my line breaks get converted to points. And if I don't use `\r\n` but just `\n` an error is thrown saying

> Cleaned hex string length is odd.

The reason why this happens is because you don't check if the line break character is just one character long in hexadecimal notation. A patch similar to this should do it:
```js
function asciiToHex(str) {
    var arr = [];
    for (var n = 0, l = str.length; n < l; n++) {
        var hex = Number(str.charCodeAt(n)).toString(16);
        if (hex.length == 2) arr.push(hex);
        else arr.push('0' + hex)
    }
    return arr.join('');
}
```

By the way the same mistake seems to be in the web pages code. :)
Greetings

**Comment by s3ansh33p** [comment]
I have fixed the issue in https://github.com/s3ansh33p/ClasspadCompiler/commit/6a67a3ac36bfe62d10454e96dcb68aca5fe2d00f
The website will require a little bit of refactoring to work with the line breaks (I will most likely change the content input to a textarea etc).
